import { AppSettings, Persona, VoiceName } from '../types';

export const SYSTEM_PERSONAS: Persona[] = [
  {
    id: 'helpful-assistant',
    name: 'Sonic Assistant',
    description: 'A cheerful, knowledgeable, and responsive conversational companion.',
    systemInstruction: 'You are Sonic, a friendly, concise, and articulate AI conversational partner. Speak naturally, keep answers concise and punchy for spoken dialogue, and engage in warm back-and-forth conversation.',
    defaultVoice: 'Zephyr',
    iconName: 'Sparkles',
    accentColor: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'english-tutor',
    name: 'English Language Coach',
    description: 'Helps practice conversational English with supportive feedback.',
    systemInstruction: 'You are an encouraging English Language Coach. Speak clearly, at a measured pace. Gently correct grammar or pronunciation if appropriate, ask engaging follow-up questions, and praise good vocabulary usage.',
    defaultVoice: 'Kore',
    iconName: 'GraduationCap',
    accentColor: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'tech-mentor',
    name: 'Senior Tech Mentor',
    description: 'Expert coding guide for software engineering, architecture, and tech news.',
    systemInstruction: 'You are a pragmatic Senior Principal Engineer and Tech Lead. Answer questions with practical insights, clean mental models, and clear verbal explanations without relying on written code blocks unless specifically requested.',
    defaultVoice: 'Puck',
    iconName: 'Code',
    accentColor: 'from-purple-500 to-violet-600',
  },
  {
    id: 'sarcastic-pirate',
    name: 'Captain Blackbeard',
    description: 'A witty, adventurous pirate captain with salty nautical humor.',
    systemInstruction: 'Ahoy! You are Captain Blackbeard, a legendary maritime rogue. Speak with hearty pirate flair ("Ahoy matey!", "Shiver me timbers!"), tell grand tales of the high seas, and stay humorously in character.',
    defaultVoice: 'Fenrir',
    iconName: 'Anchor',
    accentColor: 'from-amber-500 to-orange-600',
  },
  {
    id: 'zen-guide',
    name: 'Zen Mindfulness Guide',
    description: 'Calm, soothing voice for breathing exercises, stress relief, and focus.',
    systemInstruction: 'You are a calm, compassionate mindfulness teacher. Speak with a slow, soothing, grounded rhythm. Guide short breathing pauses when helpful and maintain a tranquil, relaxing aura.',
    defaultVoice: 'Aoede',
    iconName: 'HeartHandshake',
    accentColor: 'from-cyan-500 to-blue-500',
  },
  {
    id: 'polyglot-translator',
    name: 'Live Polyglot Translator',
    description: 'Instant live voice-to-voice translation across international languages.',
    systemInstruction: 'You are an expert real-time interpreter. Translate spoken statements accurately into the requested target language while retaining tone, nuance, and intent.',
    defaultVoice: 'Nova',
    iconName: 'Globe',
    accentColor: 'from-rose-500 to-pink-600',
  },
];

export const AVAILABLE_VOICES: { name: VoiceName; gender: string; description: string }[] = [
  { name: 'Zephyr', gender: 'Female', description: 'Warm, natural, versatile' },
  { name: 'Puck', gender: 'Male', description: 'Energetic, crisp, inquisitive' },
  { name: 'Charon', gender: 'Male', description: 'Deep, resonant, authoritative' },
  { name: 'Kore', gender: 'Female', description: 'Gentle, expressive, articulate' },
  { name: 'Fenrir', gender: 'Male', description: 'Bold, rich, theatrical' },
  { name: 'Aoede', gender: 'Female', description: 'Smooth, serene, calm' },
  { name: 'Calliope', gender: 'Female', description: 'Bright, lively, expressive' },
  { name: 'Nova', gender: 'Female', description: 'Professional, modern, clear' },
  { name: 'Ursa', gender: 'Male', description: 'Grounded, friendly, conversational' },
];

export const TRANSLATION_LANGUAGES = [
  { code: 'es', name: 'Spanish (Español)' },
  { code: 'fr', name: 'French (Français)' },
  { code: 'de', name: 'German (Deutsch)' },
  { code: 'ja', name: 'Japanese (日本語)' },
  { code: 'zh', name: 'Mandarin Chinese (中文)' },
  { code: 'it', name: 'Italian (Italiano)' },
  { code: 'pt', name: 'Portuguese (Português)' },
  { code: 'ko', name: 'Korean (한국어)' },
  { code: 'hi', name: 'Hindi (हिन्दी)' },
  { code: 'ar', name: 'Arabic (العربية)' },
  { code: 'ru', name: 'Russian (Русский)' },
];

export const DEFAULT_SETTINGS: AppSettings = {
  personaId: 'helpful-assistant',
  customInstruction: '',
  voice: 'Zephyr',
  agentFramework: 'native',
  vadSensitivity: 0.02, // RMS volume sensitivity threshold
  silenceTimeoutMs: 1200,
  enableBargeIn: true,
  enableTools: true,
  enableCodeInterpreter: true,
  enableClawCrawler: true,
  enableKnowledgeBase: true,
  autoSummarizeOnStop: true,
  translationMode: false,
  autoDetectLanguage: true,
  targetLanguage: 'Spanish',
  targetLanguageCode: 'es',
  pushToTalkMode: false,
  enableNoiseSuppression: true,
  enableVoiceIsolationGate: true,
  playbackSpeed: 1.0,
  enableCamera: false,
  enableScreenShare: false,
  theme: 'dark',
};
